id = "snowflake"
name = "Snowflake Theme"
version = "0.0.1"
schema_version = 1
authors = ["Filip Brebera"]
description = "Snowflake theme for Zed"
repository = "https://github.com/bxxf/snowflake-zed"
