id = "snowflake"
name = "Snowflake Theme"
version = "1.0.0"
schema_version = 1
authors = ["Filip Brebera <breberaf@gmail.com>"]
description = "Clean modern theme in shades of light blue and white."
repository = "https://github.com/bxxf/snowflake-zed"
